[project]
name = "minha-api"
version = "0.1.0"
description = "API de lista de tarefas com FastAPI"
readme = "README.md"
authors = [
    { name = "Geovanysilvaa", email = "lastzumbiezumbis@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"